# Generated by Django 5.1.5 on 2025-02-01 20:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_lang",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("bn", "Bengali"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("ja", "Japanese"),
                        ]
                    ),
                ),
                ("question", models.TextField(max_length=500)),
                ("answer", ckeditor.fields.RichTextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
