# Generated by Django 5.1.5 on 2025-02-01 20:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("bn", "Bengali"),
                            ("de", "German"),
                            ("it", "Italian"),
                            ("ja", "Japanese"),
                        ],
                        db_index=True,
                    ),
                ),
                ("question", models.TextField(max_length=500)),
                ("answer", ckeditor.fields.RichTextField()),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faqs.faq"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["faq", "lang"], name="faq_lang_index"),
                    models.Index(
                        fields=["lang", "question"], name="lang_question_index"
                    ),
                ],
                "unique_together": {("faq", "lang")},
            },
        ),
    ]
